import type { Product } from "./types";

/**
 * Swiss sports-nutrition product catalog.
 *
 * Products are from established Swiss brands — Sponser Sport Food (Wollerau, ZH)
 * and Winforce (Winterthur, ZH). Nutritional values and prices are approximate
 * per-serving figures used to drive recommendations and the cart; always check
 * the current label and price before a race. This list is intentionally editable
 * data, not hard-coded logic.
 */
export const CATALOG: Product[] = [
  // ---- Sponser ----
  {
    id: "sponser-competition",
    name: "Competition",
    brand: "Sponser",
    category: "drink-mix",
    phases: ["during"],
    carbsG: 36,
    sodiumMg: 250,
    multiTransportable: true,
    servingLabel: "40 g scoop in 500 ml",
    priceChf: 2.2,
    notes: "Glucose + maltodextrin + fructose isotonic mix for long sessions.",
  },
  {
    id: "sponser-isotonic",
    name: "Isotonic",
    brand: "Sponser",
    category: "drink-mix",
    phases: ["during"],
    carbsG: 26,
    sodiumMg: 300,
    servingLabel: "30 g in 500 ml",
    priceChf: 1.8,
    notes: "Light hydration mix for easy or shorter sessions.",
  },
  {
    id: "sponser-liquid-energy-plus",
    name: "Liquid Energy Plus",
    brand: "Sponser",
    category: "gel",
    phases: ["during"],
    carbsG: 26,
    sodiumMg: 100,
    servingLabel: "40 g gel",
    priceChf: 2.8,
    multiTransportable: true,
    notes: "Fast carbs on the move; take with water.",
  },
  {
    id: "sponser-liquid-energy-caffeine",
    name: "Liquid Energy BCAA / Caffeine",
    brand: "Sponser",
    category: "gel",
    phases: ["during"],
    carbsG: 26,
    sodiumMg: 100,
    caffeineMg: 50,
    servingLabel: "40 g gel",
    priceChf: 3.2,
    notes: "Carb gel with a caffeine hit for the back half of a race.",
  },
  {
    id: "sponser-salt-caps",
    name: "Salt Caps",
    brand: "Sponser",
    category: "electrolyte",
    phases: ["during"],
    carbsG: 0,
    sodiumMg: 300,
    servingLabel: "1 capsule",
    priceChf: 0.5,
    notes: "Top up sodium in heat or for heavy sweaters, independent of carbs.",
  },
  {
    id: "sponser-multi-carbo",
    name: "Multi Carbo",
    brand: "Sponser",
    category: "drink-mix",
    phases: ["pre", "during"],
    carbsG: 60,
    sodiumMg: 40,
    multiTransportable: true,
    servingLabel: "60 g in 500 ml",
    priceChf: 2.5,
    notes: "High-carb loader for carb-up and very long sessions.",
  },
  {
    id: "sponser-recovery-drink",
    name: "Recovery Drink",
    brand: "Sponser",
    category: "recovery",
    phases: ["post"],
    carbsG: 34,
    sodiumMg: 180,
    proteinG: 20,
    servingLabel: "60 g in 300 ml",
    priceChf: 3.5,
    notes: "Carb + whey/casein blend for the post-session window.",
  },
  {
    id: "sponser-oat-protein-bar",
    name: "Oat Protein Bar",
    brand: "Sponser",
    category: "bar",
    phases: ["pre", "post"],
    carbsG: 22,
    sodiumMg: 60,
    proteinG: 10,
    servingLabel: "60 g bar",
    priceChf: 3.0,
    notes: "Slower-release option before easy sessions or as a snack.",
  },

  // ---- Winforce ----
  {
    id: "winforce-carbo-basic-plus",
    name: "Carbo Basic Plus",
    brand: "Winforce",
    category: "drink-mix",
    phases: ["during"],
    carbsG: 34,
    sodiumMg: 220,
    multiTransportable: true,
    servingLabel: "40 g in 500 ml",
    priceChf: 2.1,
    notes: "Swiss multi-carb endurance drink for 60 min+ efforts.",
  },
  {
    id: "winforce-energy-gel",
    name: "Energy Gel",
    brand: "Winforce",
    category: "gel",
    phases: ["during"],
    carbsG: 24,
    sodiumMg: 90,
    multiTransportable: true,
    servingLabel: "40 g gel",
    priceChf: 2.6,
    notes: "Natural-flavour carb gel; pairs with water.",
  },
  {
    id: "winforce-power-gel-caffeine",
    name: "Power Gel Caffeine",
    brand: "Winforce",
    category: "gel",
    phases: ["during"],
    carbsG: 24,
    sodiumMg: 90,
    caffeineMg: 40,
    servingLabel: "40 g gel",
    priceChf: 2.9,
    notes: "Caffeinated gel for the final third of long races.",
  },
  {
    id: "winforce-ultra",
    name: "Ultra Drink",
    brand: "Winforce",
    category: "drink-mix",
    phases: ["during"],
    carbsG: 30,
    sodiumMg: 400,
    multiTransportable: true,
    servingLabel: "35 g in 500 ml",
    priceChf: 2.3,
    notes: "Higher-sodium mix aimed at ultra and hot-weather racing.",
  },
  {
    id: "winforce-recovery-shake",
    name: "Recovery Shake",
    brand: "Winforce",
    category: "recovery",
    phases: ["post"],
    carbsG: 30,
    sodiumMg: 150,
    proteinG: 20,
    servingLabel: "50 g in 300 ml",
    priceChf: 3.4,
    notes: "Carbohydrate + protein recovery blend.",
  },
  {
    id: "winforce-electrolytes",
    name: "Electrolytes Tab",
    brand: "Winforce",
    category: "electrolyte",
    phases: ["during"],
    carbsG: 1,
    sodiumMg: 350,
    servingLabel: "1 tab in 500 ml",
    priceChf: 0.6,
    notes: "Calorie-free hydration — good for easy sessions and weight-loss goals.",
  },
];

/** Look up a product by id. */
export function productById(id: string): Product | undefined {
  return CATALOG.find((p) => p.id === id);
}
