/**
 * Refresh the race calendar from the organisers themselves.
 *
 *   npm run refresh:events          # report only
 *   npm run refresh:events -- --write   # also rewrite src/events/confirmed.ts
 *
 * Reads each organiser's schema.org `SportsEvent` markup (the same data that
 * puts a race in Google's event results) or their `.ics` feed, and confirms the
 * date only when it clearly belongs to the race we asked about.
 *
 * **A skip is not a pass.** Every race that could not be reached, or whose page
 * was ambiguous, is reported as such and keeps its curated approximate date —
 * the one the UI already tells athletes to check. The exit code is 0 when the
 * run itself worked, because an organiser being offline is not our failure; it
 * is 1 only if nothing at all could be reached, which usually means the network
 * is blocked rather than that twelve race sites went down at once.
 */
import { writeFileSync } from "node:fs";
import { SWISS_EVENTS } from "../src/events/catalogue.ts";
import { refreshEvent } from "../src/events/sync.ts";

const write = process.argv.includes("--write");
const now = new Date();

console.log(`Refreshing ${SWISS_EVENTS.length} races from their organisers…\n`);

const results = [];
for (const event of SWISS_EVENTS) {
  // Sequential, and unhurried: this is a courtesy to a dozen small race sites,
  // not a crawl. It runs on a schedule, not on an athlete's request.
  const r = await refreshEvent(event, fetch, now);
  results.push(r);
  const mark = { confirmed: "✓", unchanged: "=", refused: "?", unreachable: "·" }[r.status];
  const detail =
    r.status === "confirmed"
      ? `${r.curatedDate} → ${r.newDate}`
      : r.status === "unchanged"
        ? `${r.curatedDate} (confirmed)`
        : `${r.curatedDate} kept — ${r.reason}`;
  console.log(`  ${mark} ${event.id.padEnd(26)} ${detail}`);
}

const confirmed = results.filter((r) => r.confirmed).map((r) => r.confirmed);
const moved = results.filter((r) => r.status === "confirmed").length;
const reached = results.filter((r) => r.status !== "unreachable").length;

console.log(
  `\n${confirmed.length} confirmed (${moved} moved), ` +
    `${results.filter((r) => r.status === "refused").length} refused, ` +
    `${results.length - reached} unreachable.`,
);

if (write) {
  const body = `import type { ConfirmedDate } from "./sync";

/**
 * Race dates fetched from the organisers themselves.
 *
 * **Generated by \`npm run refresh:events -- --write\` — do not edit by hand.**
 * Every entry carries the URL it came from and when, so a stale or wrong
 * confirmation can be traced rather than argued about. Races missing from this
 * list keep their curated approximate date, and the UI keeps telling athletes
 * to check with the organiser.
 *
 * Last run: ${now.toISOString()}
 */
export const CONFIRMED_DATES: ConfirmedDate[] = ${JSON.stringify(confirmed, null, 2)};
`;
  writeFileSync("src/events/confirmed.ts", body);
  console.log(`\nWrote src/events/confirmed.ts (${confirmed.length} entries).`);
} else if (confirmed.length > 0) {
  console.log("\nRun again with --write to apply these to src/events/confirmed.ts.");
}

if (reached === 0) {
  console.error(
    "\nNothing was reachable. That is almost certainly a blocked network rather than\n" +
      "twelve race sites being down — the dates were left exactly as curated.",
  );
  process.exit(1);
}
